# ----
# Site

title: Infosec Well-Done
url: "https://cyb3rward0g.github.io/infosec-well-done"
baseurl:
google_analytics_key:
newsletter_action:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Infosec well-done is a project to share resources with the infosec community that do not take much time to make.
author:
  name: Roberto Rodriguez
  email:
  twitter: Cyb3rWard0g
social:
  name: Infosec Well-Done
  links:
    - https://github.com/Cyb3rWard0g/infosec-well-done

# -----
# Build

timezone: Etc/UTC

paginate: 10
paginate_path: "/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
      _options:
        content:
          width: 1560
          height: 2000
        featured_image:
          width: 1560
          height: 2000
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
  #- Facebook
  #- Google Plus
  #- Instagram
  - LinkedIn
  #- Pinterest
  #- Tumblr
  - Twitter
  #- YouTube
  #- RSS

_options:
  author_image:
    width: 400
    height: 400